.PHONY: start
start:
	@echo "Starting the server..."
	@docker-compose up

.PHONY:	stop
stop:
	@echo "Stopping the server..."
	@docker-compose down

.PHONY: build
build:
	@echo "Building the server..."
	@docker-compose up --build -d
	

